export interface ProjectControlSummary {
  projectId: number;
  projectName: string;
  projectStatus: string | null;
  progress: number;
  contractConfigured: boolean;
  contractStatus: string | null;
  contractOriginalAmount: number;
  contractCurrentAmount: number;
  approvedContractAmendmentAmount: number;
  approvedContractAmendmentDays: number;
  pendingContractAmendmentCount: number;
  pendingContractAmendmentAmount: number;
  pendingContractAmendmentDays: number;
  projectedContractMargin: number | null;
  certifiedCoveragePct: number | null;
  collectedCoveragePct: number | null;
  baselineBudget: number;
  currentBudget: number;
  committedAmount: number;
  spentAmount: number;
  measuredWorkPackageCount: number;
  measuredPlannedValue: number;
  measuredEarnedValue: number;
  measuredActualCost: number;
  measuredCostVariance: number;
  measuredPlannedHours: number;
  measuredEarnedHours: number;
  measuredActualHours: number;
  productivityIndex: number | null;
  costPerformanceIndex: number | null;
  forecastFinalCost: number;
  forecastCostDelta: number;
  contractualBudgetDelta: number;
  incomes: number;
  certifiedAmount: number;
  collectedAmount: number;
  pendingCollectionAmount: number;
  overdueCollectionAmount: number;
  expenses: number;
  netCash: number;
  laborExpenses: number;
  laborHours: number;
  pendingLaborAmount: number;
  approvedLaborAmount: number;
  paidLaborAmount: number;
  procurementOrderedAmount: number;
  procurementReceivedAmount: number;
  procurementPaidAmount: number;
  pendingProcurementAmount: number;
  overdueProcurementAmount: number;
  materialsExpenses: number;
  servicesExpenses: number;
  approvedChangeDays: number;
  approvedChangeCost: number;
  pendingChangeOrders: number;
  openIncidentCount: number;
  blockedIncidentCount: number;
  criticalIncidentCount: number;
  incidentDelayDays: number;
  incidentRiskCost: number;
  weatherAffectedDays: number;
  weatherDelayDays: number;
  forecastDelayDays: number;
}
